- README.md
thanks for the great tool!
just found a minor typo.
> fix: add missing await to README

- package.json
- packages/expect-puppeteer/README.md
- packages/expect-puppeteer/src/index.js
- packages/expect-puppeteer/src/matchers/notToMatch.js
- packages/expect-puppeteer/src/matchers/notToMatch.test.js
- packages/expect-puppeteer/src/matchers/notToMatchElement.js
- packages/expect-puppeteer/src/matchers/notToMatchElement.test.js
- packages/expect-puppeteer/src/matchers/toClick.js
- packages/expect-puppeteer/src/matchers/toClick.test.js
- packages/expect-puppeteer/src/matchers/toFill.js
- packages/expect-puppeteer/src/matchers/toFill.test.js
- packages/expect-puppeteer/src/matchers/toFillForm.js
- packages/expect-puppeteer/src/matchers/toFillForm.test.js
- packages/expect-puppeteer/src/matchers/toMatch.js
- packages/expect-puppeteer/src/matchers/toMatch.test.js
- packages/expect-puppeteer/src/matchers/toMatchElement.js
- packages/expect-puppeteer/src/matchers/toMatchElement.test.js
- packages/expect-puppeteer/src/matchers/toSelect.js
- packages/expect-puppeteer/src/matchers/toSelect.test.js
- packages/expect-puppeteer/src/matchers/toUploadFile.js
- packages/expect-puppeteer/src/matchers/toUploadFile.test.js
- packages/expect-puppeteer/src/utils.js
- server/public/index.html
- Add toMatchElement method
- Make all matchers wait before an element is present
- All matchers accept an ElementHandle or a Page
> feat: add element handle support

- packages/expect-puppeteer/src/index.js
- packages/expect-puppeteer/src/index.test.js
> fix: support original Jest matchers

- README.md
Hi @neoziro,
Thanks for the awesome package, it saved me a lot of time on wiring up with Jest and Puppeteer configurations.
Meanwhile, I did take some efforts trying to figure out how to make `CustomEnvironment`, `globalSetup`, and `globalTeardown` work in my project for a while. Then I found that there's an issue https://github.com/smooth-code/jest-puppeteer/issues/15 for this, but the same problem still remains even if the issue was closed.
So I made a PR for the documentation, trying to explain how to make those test hooks work;
Please kindly take a look :)
> Docs: Explain test hooks usage in details

- package.json
- packages/expect-puppeteer/src/index.test.js
- packages/expect-puppeteer/src/utils.js
- yarn.lock
Relative to https://github.com/smooth-code/jest-puppeteer/issues/17\#issuecomment-377698539
> fix: reduce chance of collision

- packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
> fix(jest-environment-puppeteer): support slowMo

- README.md
https://docs.npmjs.com/files/package.json#dependencies says "Please do not put test harnesses or transpilers in your dependencies object. See devDependencies, below."
> Add --save-dev to npm install

- packages/expect-puppeteer/src/matchers/notToMatch.js
- packages/expect-puppeteer/src/matchers/notToMatch.test.js
- packages/expect-puppeteer/src/matchers/notToMatchElement.js
- packages/expect-puppeteer/src/matchers/notToMatchElement.test.js
- packages/expect-puppeteer/src/matchers/toMatch.js
- packages/expect-puppeteer/src/matchers/toMatch.test.js
- packages/expect-puppeteer/src/matchers/toMatchElement.js
- packages/expect-puppeteer/src/matchers/toMatchElement.test.js
- packages/expect-puppeteer/src/utils.js
> feat(expect-puppeteer): keep original error message

- packages/expect-puppeteer/src/options.js
- packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
> feat: adjust default timeout with slowMo

- README.md
Fix bad wording inside README.md
> Fix bad wording

- README.md
It took me a few minutes to figure this out so I figured it would help next TS users...
> Mention @types/expect-puppeteer in readme

- packages/jest-dev-server/README.md
- packages/jest-dev-server/src/global.js
> Adds support for protocol in jest-dev-server

- packages/jest-dev-server/src/global.js
> Fixes support for port being held by System Idle Process

- .prettierignore
- package.json
- packages/expect-puppeteer/src/index.test.js
- packages/jest-dev-server/README.md
- packages/jest-dev-server/package.json
- packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
- server/public/index.html
- yarn.lock
> Support defaultViewport

- .eslintrc.js
- README.md
- jest-puppeteer.config.js
- package.json
- packages/expect-puppeteer/src/options.js
- packages/jest-environment-puppeteer/README.md
- packages/jest-environment-puppeteer/package.json
- packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
- packages/jest-environment-puppeteer/src/readConfig.js
- packages/jest-environment-puppeteer/tests/.eslintrc.js
- packages/jest-environment-puppeteer/tests/browserContext-1.test.js
- packages/jest-environment-puppeteer/tests/browserContext-2.test.js
- packages/jest-puppeteer-preset/package.json
- packages/jest-puppeteer/package.json
relates-to: #81 and #133 
This builds on work that @Niceplace completed in #83  (thanks @Niceplace!)
I added a test for incognito isolation. I also added the `test:incognito` script which reruns all the existing tests with `incognito` as the `browserContext`. This new test script now runs in CI.
> Add incognito context support

- packages/jest-environment-puppeteer/package.json
- packages/jest-environment-puppeteer/src/readConfig.js
- yarn.lock
> My first PR to the project
Hey, started using this repository today. Jest and Puppeteer are for me, a really good replacement to selenium...
Here is what I did:
- Removed `lodash`
- Add `merge-deep`
- Run `yarn && yarn build && yarn test` and looks like everything is okay
closes https://github.com/smooth-code/jest-puppeteer/issues/139
> Removing lodash dependency

- README.md
Adds a quick explanation of how to setup `jest-puppeteer` on CI environment. This addresses #122 .
N/A
> Add CI workers limit setup

- packages/jest-dev-server/README.md
documents problem solved in https://github.com/smooth-code/jest-puppeteer/commit/cceb0bd0ad181963326b229eb16d6346a61d0659 and documented: https://github.com/smooth-code/jest-puppeteer/issues/96
> updates readme with troubleshooting section

- .eslintrc.js
- BACKERS.md
- README.md
- package.json
- packages/expect-puppeteer/src/options.js
- packages/jest-dev-server/README.md
- packages/jest-dev-server/src/global.js
- packages/jest-environment-puppeteer/README.md
- packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
- packages/jest-environment-puppeteer/src/readConfig.js
- packages/jest-environment-puppeteer/tests/.eslintrc.js
- packages/jest-environment-puppeteer/tests/readConfig.test.js
- yarn.lock
> chore: upgrade deps

- packages/jest-dev-server/package.json
- yarn.lock
There is an ongoing issue with event-stream since a malicious person took over, see 
https://github.com/dwyl/terminate/pull/36 
https://github.com/indexzero/ps-tree/pull/34
https://github.com/dominictarr/event-stream/issues/116
> upgrade terminate

- packages/jest-environment-puppeteer/README.md
- packages/jest-environment-puppeteer/src/readConfig.js
- packages/jest-environment-puppeteer/tests/__fixtures__/promiseConfig.js
- packages/jest-environment-puppeteer/tests/readConfig.test.js
This solves #176 
The change was implemented in TDD.
> Accept a promise as config

- LICENSE
> 2018 -> 2019

- README.md
- packages/expect-puppeteer/README.md
close https://github.com/smooth-code/jest-puppeteer/issues/202
> chore: update readme

- packages/jest-dev-server/package.json
- packages/jest-dev-server/src/global.js
- yarn.lock
as for suggest https://github.com/smooth-code/jest-puppeteer/issues/124, use `wait-on` instead of `wait-port`.
> chore: use wait-on instead of wait-for

- packages/expect-puppeteer/README.md
- packages/expect-puppeteer/src/matchers/toClick.test.js
- packages/expect-puppeteer/src/matchers/toMatchElement.js
#132 
Implements the support of xpath according to this ticket. 
I need to add more tests for all matchers & change doc but first I want to know if the click test & xpath selectors is ok.
Thanks you for your time & your work.
> Support XPATH selectors

- README.md
> Update readme with command to install types

- package.json
- packages/jest-puppeteer-preset/package.json
- packages/jest-puppeteer/package.json
- yarn.lock
> fix: update puppeteer version

- packages/expect-puppeteer/src/matchers/toFill.js
- packages/expect-puppeteer/src/matchers/toFill.test.js
- server/public/index.html
Fix toFill on a multiline textarea
fixes #150
> fix: fix toFill on textarea

- packages/expect-puppeteer/README.md
> chore(readme): add note about matching outer element

- examples/create-react-app/package.json
- packages/jest-environment-puppeteer/package.json
> chore: update example deps

- README.md
- added readme instructions for Typescript users who get errors like 'page is undefined' when testing out the example code.
- added a code sample for people who are using their own setupFiles to use multiple Jest projects 
no test plan, since it was just a readme update
> chore(readme): add react-scripts fix to readme

- README.md
First of all, thanks for `jest-puppeteer`! Really nice to have an easy way of setting up Puppeteer along with Jest as a test runner.
The docs in the readme are a bit unclear about the `jest-puppeteer.config.js` code block - it isn't very clear that these are default values.
I added a few words and a new title for the code block to indicate that the config is default values.
I tried reading my edited version of the docs a few times to check if it's clearer.
> Clarify default values of jest-puppeteer.config.js

- packages/jest-environment-puppeteer/README.md
fix missing links in documents
> fix missing links

- packages/jest-puppeteer/.npmignore
- packages/jest-puppeteer/package.json
> fix: fix preset export

- README.md
- packages/jest-environment-puppeteer/README.md
> docs: update config doc

- packages/jest-environment-puppeteer/src/env.ts
Fixes `PuppeteerEnvironment["global"]` types to resolve:
* https://github.com/argos-ci/jest-puppeteer/issues/548
I've also initialised `puppeteerConfig` and `jestPuppeteer` in the constructor as these are required
> Compiler errors accessing `PuppeteerEnvironment` globals

- .github/workflows/ci.yml
- README.md
- jest-puppeteer.config.js
- package-lock.json
- package.json
- packages/expect-puppeteer/package.json
- packages/expect-puppeteer/rollup.config.mjs
- packages/jest-dev-server/README.md
- packages/jest-dev-server/package.json
- packages/jest-dev-server/rollup.config.mjs
- packages/jest-dev-server/src/index.ts
- packages/jest-environment-puppeteer/README.md
- packages/jest-environment-puppeteer/package.json
- packages/jest-environment-puppeteer/rollup.config.mjs
- packages/jest-puppeteer/package.json
- packages/jest-puppeteer/rollup.config.mjs
- packages/spawnd/package.json
- packages/spawnd/rollup.config.mjs
- packages/spawnd/src/index.ts
- fix(jest-dev-server): no default host
- feat: drop Node.js v14 support
> Fix default host, upgrade deps and drop Node.js v14

- packages/jest-dev-server/src/index.ts
> fix(jest-dev-server): fix config types

- LICENSE
- packages/expect-puppeteer/LICENSE
- packages/expect-puppeteer/package.json
- packages/jest-dev-server/LICENSE
- packages/jest-dev-server/package.json
- packages/jest-environment-puppeteer/LICENSE
- packages/jest-environment-puppeteer/package.json
- packages/jest-puppeteer/LICENSE
- packages/jest-puppeteer/package.json
- packages/spawnd/LICENSE
- packages/spawnd/package.json
> chore: update license
