argos-ci/jest-puppeteer

packages/expect-puppeteer/src/matchers/notToMatch.js, packages/expect-puppeteer/src/matchers/toMatch.js
```
TypeError: Cannot read property 'textContent' of null
```
Also, thank you for finally making Jest with Puppeteer feasible. I tried setting this up a few times before and had a really hard time.
=> The `document.body` can be undefined when using `toMatch`

packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
This is adding the ignoreHTTPSErrors option to the launch config to allow for local testing with self-signed certificate
=> Adding ignoreHTTPSErrors launch option

README.md, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/src/readConfig.js, packages/jest-environment-puppeteer/tests/__fixtures__/customConfig.js, packages/jest-environment-puppeteer/tests/readConfig.test.js
=> feat(jest-environment-puppeteer): support custom config

packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js, packages/jest-environment-puppeteer/src/readConfig.js
=> feat(jest-environment-puppeteer): added config option for global err msg

.eslintignore, README.md, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/package.json, packages/jest-environment-puppeteer/src/global.js, yarn.lock
=> feat(jest-environment-puppeteer): add server.launchTimeout & server.debug options

packages/expect-puppeteer/README.md, packages/expect-puppeteer/src/matchers/toFill.js, packages/expect-puppeteer/src/matchers/toFill.test.js
Sometimes (I'd guess due to slow hardware), our builds will fail because `toFill` will end up typing characters out of order in input elements. This PR exposes the `delay` attribute so we can introduce throttling of typing events such that the events do not occur out of order.
=> feat(expect-puppeteer): added delay option to element.type for toFill matcher

README.md
This fixes the [fresh install problem](https://github.com/smooth-code/jest-puppeteer/issues/42#issuecomment-384057308).
The README.md assumes that jest is installed locally. If someone wants to try out jest-puppeteer in a new directory, jest won't be installed locally. To fix fresh install problem, one of these things need to happen:
- Remove peer dependencies (my ideal)
- Add jest-environment-node to jest-puppeteer command (this PR)
- Add jest to npm install command
=> Add jest to npm install command

packages/expect-puppeteer/README.md, packages/expect-puppeteer/src/matchers/toMatchElement.js, packages/expect-puppeteer/src/matchers/toMatchElement.test.js
BREAKING CHANGE: Text is now trimmed and no longer evaluated as a RegExp. If you want this behaviour, use a true RegExp.
Closes #51
Closes #50
=> feat(expect-puppeteer): enhance toMatchElement / toClick text option

packages/jest-environment-puppeteer/src/constants.js
Allows multiple Jest processes to connect to their own chromium instances
=> Use PID based wsEndpoint file

README.md, packages/expect-puppeteer/src/options.js, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js, packages/jest-environment-puppeteer/src/global.js, packages/jest-environment-puppeteer/src/readConfig.js
See https://github.com/smooth-code/jest-puppeteer/issues/99 for discussion.
=> #99 Add ability to connect to an already existing instance of Chrome

packages/jest-environment-puppeteer/src/readConfig.js, packages/jest-environment-puppeteer/tests/readConfig.test.js
This flags were added to default config:
```js
'--disable-background-timer-throttling'
'--disable-backgrounding-occluded-windows'
'--disable-renderer-backgrounding'
```
I created a test to make sure that everything is okay with `launch.args`.
fixes https://github.com/smooth-code/jest-puppeteer/issues/137
=> Disable tab throttling

packages/jest-dev-server/src/global.js
Avoid prompting for super user password when possible.
TBD
=> Only run findProcess where required in order to avoid prompting for super user login

packages/jest-puppeteer/LICENSE
Adds the MIT license file so that the package is licensed.
=> Add LICENSE file to jest-puppeteer package

packages/jest-environment-puppeteer/src/global.js
Use `.disconnect` method in teardown phase, as a complement to the `.connect` method in the setup phase.
This allows long-running external instances of chromium to be managed independently of the jest test runner, and/or possible reuse of the chromium instances across different test runs and projects.
For example, our use case it to run multiple chromium instances (similar to selenium's grid) and allow different projects to `connect` and run their test suites against the grid. 
See pptr docs:
https://pptr.dev/#?product=Puppeteer&version=v1.11.0&show=api-browserdisconnect
Running an external browser, which jest-puppeteer can connect to and at the end of the test suite, the browser remains open.
=> fix: skip closing external browser on teardown

jest-puppeteer.config.js, packages/jest-dev-server/README.md, packages/jest-dev-server/src/global.js
support multiple servers and compatible with older versions
see https://github.com/smooth-code/jest-puppeteer/issues/134
=> feat:support multiple servers

packages/jest-dev-server/package.json, packages/jest-dev-server/src/global.js, packages/spawnd/package.json, packages/spawnd/src/index.js, yarn.lock
- Remove dependencies to `terminate` by using another package that is more permissive [`tree-kill`](https://www.npmjs.com/package/tree-kill).
- Closes #167.
- `yarn test` exits cleanly
=> Remove dependency to terminate

packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
Environment setup and teardown should be symmetric. Since we connect to the browser on setup, we should disconnect on teardown. I'm not sure if it has actual implications but it seems like the right thing to do.
There are no explicit tests for that area, although existing tests should continue to pass. They will fail if this new code is broken (verified).
=> Disconnect the browser on environment teardown

examples/create-react-app/package.json, packages/jest-environment-puppeteer/src/global.js
close https://github.com/smooth-code/jest-puppeteer/issues/181
- ```npm run test:integrationWithWatch``` is running normally in cra example
=> fix: Jest --watch fails to reload

packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
see https://github.com/smooth-code/jest-puppeteer/issues/184
=> fix: wrong timeout when using jestPuppeteer.debug()

README.md
Hey, pretty simple: Since https://github.com/smooth-code/jest-puppeteer/commit/cc9bbfa493349cc88273120996e713523cf86714 `jest-puppeteer`'s `globalSetup` needs `jest`'s `globalConfig`. If a user creates their own config they should pass `jest`'s `globalConfig`.
=> Adjust example on README.md to pass globalConfig

README.md
Resolves #162.
I just got confused by this issue too, which made for a somewhat rocky first impression of the tool. Maybe this additional warning would help?
None, it's docs :)
=> Warn new users that they need to remove `testEnvironment` from Jest configuration

packages/jest-environment-puppeteer/src/global.js
close https://github.com/smooth-code/jest-puppeteer/issues/195
=> fix: Cannot read property watch of undefined in jest v22 version

README.md
This clarifies the documentation around custom setup files. First, you only need to do it if you're customizing one of the two setup properties. Secondly, `setupTestFrameworkScriptFile` is now deprecated in favor `setupFilesAfterEnv` so I figured it was good to add that to the docs:
https://jestjs.io/docs/en/configuration#setupfilesafterenv-array
N/A as this is a documentation change?
=> docs: clarify setup file customization

packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
Specifying both options `browserURL` and `browserWSEndpoint` is invalid when calling connect. Since `PuppeteerEnvironment` always gets a WS endpoint prepared from global setup, we must unset the `browserURL` option.
Edit: Since this problem also exists in v3, it would be nice to backport this, since v4 does not support jest v23 anymore
Edit2: This most likely fixes #200, at least my occurence of it. The real problem is that setup exceptions get swallowed, if teardown also throws. Guessing that the jest code looks something like this:
```js
try {
env.setup();
test();
} catch(e) {
env.teardown();
throw e;
}
```
So the actual problem (setup failing) gets shadowed by the teardown fragility not being able to do its work on a dirty env.
=> fix invalid connect options, when using browserURL

.gitignore, packages/expect-puppeteer/README.md, packages/expect-puppeteer/src/matchers/toMatchElement.js, packages/expect-puppeteer/src/matchers/toMatchElement.test.js, server/public/index.html
Add visible options to toMatchElement config,.
wait for element to be present in DOM and to be visible, i.e. to not have `display: none` or `visibility: hidden` CSS properties. Defaults to `false`.
see https://github.com/smooth-code/jest-puppeteer/issues/207
see test case
=> feat: Add visible options to toMatchElement config

packages/jest-dev-server/package.json, packages/jest-dev-server/src/global.js, yarn.lock
Reduce the number of jest-dev-server dependencies by half by replacing `inquirer` package with `prompts` .
jest-dev-server currently uses [inquirer](https://www.npmjs.com/package/inquirer) to display prompt when `usedPortAction='ask'`. This package has 26 dependencies (see: http://npm.broofa.com/?q=inquirer@6.2.2) which account for about half (!) of all dependencies of jest-dev-server (see: http://npm.broofa.com/?q=jest-dev-server@4.0.0). This seems a lot for such a minor feature.
By replacing inquirer with [prompts](https://www.npmjs.com/package/prompts), we can drastically reduce this number. Prompts is well established project, with over 10M downloads per months and 300 direct dependents. By looking at the number of open issues and PR,  it also seems to be better maintained that …
=> chore(jest-dev-server): reduce number of deps by replacing inquirer with prompts

packages/jest-dev-server/src/global.js
I have a dev server already running and used `usedPortAction: 'ignore'` but the server is still attempted to be started despite the port showing as being taken. This patch puts a fork in the code to _not_ attempt to start the server if `ignore` is used and `isPortTaken` is `true`.
Start a server on a given port. Then attempt to use the same port in jest-dev-server config using `usedPortAction: 'ignore'`. Without the patch, the code will throw an `EADDRINUSE` error. This is because it will still attempt to run the given command. With the patch, it will simply run the tests.
For now, I'm just trapping the `EADDRINUSE` error for my `command` (in this specific case it is an express.js server):
```
command: `node -e "server = require('./server');server.listen(${config.get('ports.server')}).on(' …
```
=> Do not attempt to start the server when `usedPortAction` is `ignore` and `isPortTaken` is `true`

packages/jest-dev-server/README.md, packages/jest-dev-server/src/global.js
see https://github.com/smooth-code/jest-puppeteer/issues/228
=> feat: add waitOnScheme options

packages/jest-dev-server/README.md, packages/jest-dev-server/src/global.js
see https://github.com/smooth-code/jest-puppeteer/issues/233
this [repo](https://github.com/Dilatorily/jest-puppeteer-issue) can run normally
=> fix: jest-dev-server can't detect used ports

package.json, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/package.json, packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js, packages/jest-environment-puppeteer/src/global.js, packages/jest-environment-puppeteer/src/readConfig.js, packages/jest-environment-puppeteer/tests/readConfig.test.js, yarn.lock
This patch adds a new option to `jest-puppeteer.config.js` - `browser`. The option might be either `'chromium'` or `'firefox'` (case-insensetive) and defaults to `'chromium'`. Depending on this option, either `puppeteer` or `puppeteer-firefox` will be used to drive test execution.
There's a unit test in the PR. Let me know if/how I should add an integration test.
Fixes #171
=> feat: support "browser" config option

README.md, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js, packages/jest-environment-puppeteer/tests/resetBrowser.test.js
Add `jestPuppeteer.resetBrowser()` function to reset the `global.browser` object according to the configuration.
`global.browser` is is setup based on the configuration.
```js
this.global.browser = await puppeteer.connect({
...config.connect,
...config.launch,
browserURL: undefined,
browserWSEndpoint: wsEndpoint,
})
```
This will allow the browser to be reset by the user and ensure the `global.browser` object will be the same after this call as the when it was first setup.
Users can reset the `global.browser` object before each test by calling `jestPuppeteer.resetBrowser()` in a `beforeEach` function easily.
```js
beforeEach(async () => {
await jestPuppeteer.resetBrowser()
})
```
fixes https://github.com/smooth-code/jest-puppeteer/pull/183#issuecomment-490210920
```js …
```
=> resetBrowser

packages/jest-dev-server/src/global.js
Problem 1: 
When setting up a dev server a host value can be provided. However, the check to see if a port is already in use does not consider this host value. This leads to ports that are in use falsely being reported as free and then a `EARINUSE` failure.
Problem 2: 
`userPortAction: 'kill'` also results in a `EARINUSE` failure. This is due to the server being started before waiting for the existing process to be killed. 
- Start a server on a specific host and port. 
- Provide the host and port in the jest-dev-server config and set `usedPortAction: 'kill'`, e.g.
`module.exports = {
server: {
usedPortAction: 'kill',
command: 'npm start',
host: 'test.host',
port: 8989
}
};`
- Run the tests
**Expected Behaviour**
Running the tests should: 
1. kill the conflicting process
2. start a new …
=> feat: use host in port check

packages/jest-environment-puppeteer/src/global.js
Fixes #269.
When jest is running with `--watch`, each test run creates a new browser — so we’ll want to teardown the browser to avoid memory leaks.
I manually tested this — not sure how to write an automated test since it involves the setup and teardown process itself.
- I started the dev server by running `PORT=4444 node server`, since the dev server is not started in `--watch` mode (see #229).
- In another terminal window, I ran `yarn test --watch`.
- Observe that the browser is closed at the end of a test run.
- I hit `a` to re-run all tests.
- Observe a new browser is started, the tests are run, and it is closed.
- Repeat forever!
=> Teardown browser in watch mode.

packages/expect-puppeteer/src/index.js, packages/expect-puppeteer/src/matchers/notToMatch.test.js, packages/expect-puppeteer/src/matchers/notToMatchElement.test.js, packages/expect-puppeteer/src/matchers/setupPage.js, packages/expect-puppeteer/src/matchers/toClick.test.js, packages/expect-puppeteer/src/matchers/toFill.test.js, packages/expect-puppeteer/src/matchers/toFillForm.test.js, packages/expect-puppeteer/src/matchers/toMatch.test.js, packages/expect-puppeteer/src/matchers/toMatchElement.test.js, packages/expect-puppeteer/src/matchers/toSelect.js, packages/expect-puppeteer/src/matchers/toSelect.test.js, packages/expect-puppeteer/src/matchers/toUploadFile.test.js, packages/expect-puppeteer/src/utils.js, server/public/frame.html
When I pass child frame instance to expectPuppeteer, I get error `Frame is not supported`.
```
const frame = page.frames().find(frame => frame.name() === 'myframe');
const text = expectPuppeteer(frame).toClick('.selector');
```
=> add support child frames

.travis.yml, examples/create-react-app/package.json, examples/create-react-app/yarn.lock, package.json, packages/expect-puppeteer/src/matchers/toClick.test.js, packages/jest-puppeteer-preset/package.json, packages/jest-puppeteer/package.json, yarn.lock
Currently `peerDependencies` only allows `"puppeteer": "^1.5.0"`.
Puppeteer v2 was released yesterday:
https://github.com/GoogleChrome/puppeteer/releases/tag/v2.0.0
It drops support for Node.js 6, and since **jest-puppeteer** only supports Node.js 8+ anyway we can make this a non-breaking change.
Currently, **jest-puppeteer** runs its tests using `puppeteer@1.18.1`, so a puppeteer upgrade actually causes a breakage in `page.waitForSelector('html')` where `page` is a frame.
It seems to be hitting this bug: https://github.com/GoogleChrome/puppeteer/issues/2602
But the following quick fix resolves the issues:
**Before**
```js
await page.waitForSelector('html')
```
Which causes a protocol error:
```
• toClick › Frame › should click using text
Protocol error (DOM.resolveNode): Node with given …
```
=> Increase peerDependencies to allow Puppeteer v2

packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js
`stdin.setRawMode` doesn't exist and throws if stdin is not TTY:
```
TypeError: stdin.setRawMode is not a function
at node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:82:19
at Object.debug (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:61:16)
```
=> Only call setRawMode if stdin is TTY

packages/jest-environment-puppeteer/src/global.js
Fixes #229, fixes #181.
The `jest /tests/endtoend/** --watch` command will:
1. Start up the servers I defined in `jest-puppeteer.config.js`.
2. And, if I save some test file, - it will successfully rerun the tests (while defined servers are running) - https://github.com/smooth-code/jest-puppeteer/pull/298 PR fails this test for me.
=> Fixes --watch mode server start&restarts

README.md
Adds documentation on the `browser` config field added in PR #220.
Review "Configure Puppeteer" section in the README.
=> Add browser config documentation

packages/jest-environment-puppeteer/src/readConfig.js
This is because sometimes we prefer `puppeteer-core` as a dependency instead of `puppeteer`.
=> fix: require  to `puppeteer-core` as fallback

README.md, package.json, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js, packages/jest-environment-puppeteer/src/global.js, packages/jest-environment-puppeteer/src/readConfig.js, packages/jest-environment-puppeteer/tests/__fixtures__/browserConfig.js, packages/jest-environment-puppeteer/tests/__fixtures__/browserConfigChromium.js, packages/jest-environment-puppeteer/tests/__fixtures__/browserLaunchConfig.js, packages/jest-environment-puppeteer/tests/__fixtures__/browserLaunchProductConfig.js, packages/jest-environment-puppeteer/tests/__fixtures__/invalidProduct.js, packages/jest-environment-puppeteer/tests/readConfig.test.js
This PR is to address https://github.com/smooth-code/jest-puppeteer/issues/312.  Puppeteer now supports firefox natively.  As such, support for puppeteer-firefox is no longer required.  This PR replaces the `browser` property in `jest-puppeteer.config.js` in favor of the native `launch.product` key.
All existing tests pass and a new test was added to ensure that the `launch.product` value matches either `firefox` or `chrome`.
=> fix: Leverage Puppeteer's native support for Firefox

packages/jest-environment-puppeteer/package.json
Add `jest-environment-node` as a dependency of `jest-environment-puppeteer`
fixes #396
=> fix: add jest-environment-node as a dependency

packages/expect-puppeteer/src/matchers/toFill.js
fixes https://github.com/smooth-code/jest-puppeteer/pull/381#issuecomment-828420893
=> fix: use Delete to clear input instead of Backspace

.eslintrc.js, packages/expect-puppeteer/src/matchers/toFill.js, packages/expect-puppeteer/src/matchers/toFill.test.js, server/public/index.html
toFill number input
fixes #411
added test
=> fix: fix toFill on number input

README.md, packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js, packages/jest-environment-puppeteer/src/global.js
Hello. I faced the problem described in [issue](https://github.com/smooth-code/jest-puppeteer/issues/409). 
In my case i cant run tests with multiple workers because the tests will affect to each other.  From different browsers i will be able to run tests from diffrent users.
I first implemented the feature system in my project. For example run tests with `--runInBand or -w 1`
And workers count = 2 `-w 2`
If the number of workers is greater than the number of test cases in `setup.js`, more browser instances will be launched than will be used.
I tried to move the browser launch to `PuppeteerEnvironmet.js`, but there is no information about the launched browsers in` global.teardown` due to different contexts.
=> Browser instance per Jest worker

packages/jest-environment-puppeteer/src/global.js
Address #388 
Expect the test to close properly without `Navigation failed because browser has disconnected!` exceptions
=> fix: Catch exceptions on browser close or disconnect during teardown

packages/jest-environment-puppeteer/src/global.js
As per comment @IljaKroonen, `disconnect()` does not return a `Promise`. Reverted modification
`disconnect()` references:
-  https://github.com/puppeteer/puppeteer/blob/943477cc1eb4b129870142873b3554737d5ef252/test/browser.spec.ts#L77
- https://github.com/puppeteer/puppeteer/blob/943477cc1eb4b129870142873b3554737d5ef252/src/common/Browser.ts#L538
=> fix: Revert catch on disconnect

README.md
This PR updates the README.md to make more visible the option `exitOnPageError`.
=> Update README: add exitOnPageError flag

packages/jest-dev-server/src/global.js
Fixes problem with filling up processes buffer.
If process created by `jest-dev-server` with `debug=false` option writes something to `stdout`, it will stop responding after some time. Reading from `stdout` and doing nothing with it fixes the problem
Run any process with `setup` function from `jest-dev-server` with both `debug=true` and `false`. Should spawn process in both cases
=> [jest-dev-server] read from server's stdout to prevent buffer from filling up

packages/expect-puppeteer/src/index.js, packages/expect-puppeteer/src/matchers/notToMatch.test.js, packages/expect-puppeteer/src/matchers/notToMatchElement.test.js, packages/expect-puppeteer/src/matchers/toClick.test.js, packages/expect-puppeteer/src/matchers/toFill.test.js, packages/expect-puppeteer/src/matchers/toFillForm.test.js, packages/expect-puppeteer/src/matchers/toMatch.test.js, packages/expect-puppeteer/src/matchers/toMatchElement.test.js, packages/expect-puppeteer/src/matchers/toSelect.test.js
Currently, errors thrown from matchers have a corrupt stack trace, making it impossible for the developer to tell which line of the test caused the error. 
e.g.:
With the fix, the errors look good, with all the stack trace info:
This bug is caused by calling `Error.captureStackTrace` with the wrong 2nd parameter. Unfortunately, since `createMatcher` is not part of the stack trace, the entire stack trace is removed. `createMatcher` will never be part of the stack trace, the function that should be removed from the trace is the inner function, `throwingMatcher`.
=> fix(expect-puppeteer): return proper error stack traces from matchers

README.md
=> docs(readme): fix puppeteer docs 404 links

packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js, packages/jest-environment-puppeteer/tests/runBeforeUnload.test.js, packages/jest-environment-puppeteer/tests/runBeforeUnloadOnClose.test.js
Closes https://github.com/smooth-code/jest-puppeteer/issues/362
Introduce a new option `runBeforeUnloadOnClose` that controls whether or not `page.close` should be called with `runBeforeUnload: true`
Tests were added:
=> Add option `runBeforeUnloadOnClose`

packages/jest-dev-server/src/index.js
=> fix(jest-dev-server): fix port detection

packages/jest-dev-server/README.md
We've noticed the module-scoped [`const servers = []`](https://github.com/argos-ci/jest-puppeteer/blob/v7.0.1/packages/jest-dev-server/src/index.js#LL43C19-L43C20) was removed in v8.0.0
* https://github.com/alphagov/govuk-frontend/pull/3363#pullrequestreview-1326812806
With this gone, it's no longer possible to run `teardown()` without providing a list of processes
This PR updates the documentation to:
1. Remove references to `getServers()`
2. Update examples to add server processes to `globalThis`
This is nicely inline with the Jest `globalSetup` example too:
https://jestjs.io/docs/configuration#globalsetup-string
Fixes: https://github.com/argos-ci/jest-puppeteer/issues/529
=> docs(jest-dev-server): update teardown docs with servers global

README.md, packages/jest-dev-server/README.md
Fixes documentation for the `setup` and `teardown` global hooks to resolve:
* https://github.com/argos-ci/jest-puppeteer/issues/534
Additionally, the changes in https://github.com/argos-ci/jest-puppeteer/commit/d256469c1de4b36d0218e58fb43aa1482338fd7d now throw:
```console
TypeError: Jest: Got error running globalSetup - /path/to/project/config/jest/browser/open.js, reason: globalSetup file must export a function at /path/to/project/config/jest/browser/open.js
at /path/to/project/node_modules/@jest/core/build/runGlobalHook.js:105:21
```
So I've switched the docs back to ~`const options = `~ `module.exports = `
=> Document moved `setup` and `teardown` exports for global hooks

README.md, packages/expect-puppeteer/README.md
- docs(expect-puppeteer): fix links in readme
- docs(readme): fix `toMatch` -> `toMatchTextContent`
=> fix to match doc

packages/jest-environment-puppeteer/package.json
The homepage link in the package results in a 404 error as the directory name had been cut off.
–
=> fix: correct homepage link which was missing full dir name

.github/workflows/ci.yml, README.md, package-lock.json, package.json, packages/expect-puppeteer/package.json, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/src/env.ts, server/public/shadow.html
From the [`puppeteer@22` release](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.0.0) we have two main breaking changes + docs:
1. Replace Node.js v16 with v20 in GitHub Actions
2. Document that `headless: 'new'` is now `headless: true`
3. Switch to ~`browser.createIncognitoBrowserContext()`~ `browser.createBrowserContext()`
I've added feature detection for `"createBrowserContext" in browser` to maintain support for Puppeteer <= v21
=> Add Puppeteer v22 compatibility

.gitignore, package-lock.json, package.json, packages/expect-puppeteer/jest.config.js, packages/expect-puppeteer/package.json, packages/expect-puppeteer/src/matchers/test-util.ts, packages/expect-puppeteer/src/matchers/toClick.test.ts, packages/expect-puppeteer/src/matchers/toFill.ts, packages/jest-dev-server/package.json, packages/jest-environment-puppeteer/package.json, packages/jest-environment-puppeteer/src/browsers.ts, packages/jest-environment-puppeteer/src/env.ts, packages/jest-puppeteer/package.json, packages/spawnd/package.json
=> feat: support puppeteer v23

README.md, package-lock.json, package.json, packages/expect-puppeteer/src/index.test.ts, packages/expect-puppeteer/src/index.ts, packages/expect-puppeteer/src/matchers/notToMatchElement.test.ts, packages/expect-puppeteer/src/matchers/notToMatchTextContent.test.ts, packages/expect-puppeteer/src/matchers/toClick.test.ts, packages/expect-puppeteer/src/matchers/toFill.test.ts, packages/expect-puppeteer/src/matchers/toFillForm.test.ts, packages/expect-puppeteer/src/matchers/toMatchElement.test.ts, packages/expect-puppeteer/src/matchers/toMatchTextContent.test.ts, packages/expect-puppeteer/src/matchers/toSelect.test.ts, packages/expect-puppeteer/src/matchers/toUploadFile.test.ts, packages/expect-puppeteer/src/options.test.ts, packages/jest-environment-puppeteer/tests/.eslintrc.js, packages/jest-environment-puppeteer/tests/basic.test.ts, packages/jest-environment-puppeteer/tests/browserContext-1.test.ts, packages/jest-environment-puppeteer/tests/browserContext-2.test.ts, packages/jest-environment-puppeteer/tests/config.test.ts, packages/jest-environment-puppeteer/tests/resetBrowser.test.ts, packages/jest-environment-puppeteer/tests/resetPage.test.ts, packages/jest-environment-puppeteer/tests/runBeforeUnloadOnClose.test.ts
This pull request contains :
1. A refactoring of the ```expect-puppeteer``` types so that types resolution for the puppeteer matchers work in Typescript (issue [598](https://github.com/argos-ci/jest-puppeteer/issues/598)).
2. Additional type assertions on the ```Error``` objects in the tests to eliminate ```any``` types and comply to ```@typescript-eslint/recommended```.
3. A few upgrades of deprecated methods on the puppeteer API (see ```resetBrowser.test.ts```).
4. An update on the main README to reflect the changes.
1. No breaking changes or regressions should occur since the implementation was left untouched, only types declarations were changed.
2. Test suite passes 100%.
3. When testing the [minimal repo](https://github.com/mulekick/jest-puppeteer-issue) with the following …
=> fix types resolution for expect-puppeteer

README.md, packages/expect-puppeteer/README.md, packages/expect-puppeteer/src/index.test.ts, packages/expect-puppeteer/src/index.ts, packages/expect-puppeteer/src/matchers/toClick.ts, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/tests/basic.test.ts, packages/jest-environment-puppeteer/tests/browserContext-1.test.ts, packages/jest-environment-puppeteer/tests/browserContext-2.test.ts, packages/jest-environment-puppeteer/tests/config.test.ts, packages/jest-environment-puppeteer/tests/resetBrowser.test.ts, packages/jest-environment-puppeteer/tests/resetPage.test.ts, packages/jest-environment-puppeteer/tests/runBeforeUnloadOnClose.test.ts
This pull request contains :
1. An additional module declaration that adds support for ```expect-puppeteer``` matchers types resolution when jest types are imported from ```@jest/globals``` (issue [601](https://github.com/argos-ci/jest-puppeteer/issues/601)).
2. As a result, installing ```@types/jest``` is no longer mandatory and the project is now 100% compliant to [jest official recommendations](https://jestjs.io/docs/next/getting-started#type-definitions).
3. Edits of the main README and the ```jest-environment-puppeteer``` README to describe how to set up with typescript in a more detailed way.
4. An edit of the ```expect-puppeteer``` README to adhere to the current API and point to the new puppeteer docs.
5. Removals of the ```expect-puppeteer``` imports in the test files that do not …
=> Fix types resolution when importing jest types from @jest/globals

README.md, packages/expect-puppeteer/README.md, packages/expect-puppeteer/src/globals.test.ts, packages/expect-puppeteer/src/index.test.ts, packages/expect-puppeteer/src/index.ts, packages/expect-puppeteer/src/matchers/toClick.ts, packages/jest-environment-puppeteer/README.md, packages/jest-environment-puppeteer/tests/basic.test.ts, packages/jest-environment-puppeteer/tests/browserContext-1.test.ts, packages/jest-environment-puppeteer/tests/browserContext-2.test.ts, packages/jest-environment-puppeteer/tests/config.test.ts, packages/jest-environment-puppeteer/tests/resetBrowser.test.ts, packages/jest-environment-puppeteer/tests/resetPage.test.ts, packages/jest-environment-puppeteer/tests/runBeforeUnloadOnClose.test.ts
This pull request contains :
1. The diff between `10.1.2` and `10.1.3` minus the non-working additional declaration for `@jest/globals` imports support (see [602](https://github.com/argos-ci/jest-puppeteer/pull/602))
2. An edit of the rewritten main README to fix the example tests, remove any reference to the use of `@jest/globals` for imports and explicitly mention that it is not supported.
3. An edit of the `jest-environment-puppeteer` README to align with the current recommended setup for Typescript and point to the new puppeteer docs.
4. An additional basic test for the `expect-puppeteer` matchers with `@jest/globals` imports, disabled for now. 
1. Test suite passes 100%.
=> reinstate diff between 10.1.2 and 10.1.3 minus @jest/globals support + misc

.github/workflows/ci.yml, README.md, jest-puppeteer.config.js, package-lock.json, package.json, packages/expect-puppeteer/package.json, packages/jest-dev-server/package.json, packages/jest-environment-puppeteer/package.json, packages/jest-environment-puppeteer/tests/__fixtures__/browserConfig.js, packages/jest-environment-puppeteer/tests/__fixtures__/invalidProduct.js, packages/jest-environment-puppeteer/tests/__fixtures__/launchConfig.js, packages/jest-environment-puppeteer/tests/config.test.ts, packages/jest-puppeteer/package.json, packages/spawnd/package.json
BREAKING CHANGE: Node.js v16 is not supported
Fix #607
=> feat: add support for Node.js v22-23
